server:
  port: 8761
  compression:
    enabled: true
    mime-types: application/json,application/xml,text/html,text/xml,text/plain

eureka:
  client:
    registerWithEureka: true
    fetchRegistry: false
  server:
    waitTimeInMsWhenSyncEmpty: 0

spring:
  application:
    name: eureka-server
  cloud:
      config:
        enabled: true
        discovery:
          enabled: true
          serviceId: SAMPLE-HYSTRIX-CONFIG
