debug: true
server:
  compression:
    enabled: true
    mime-types: application/json,application/xml,text/html,text/xml,text/plain

spring:
  aop:
    proxy-target-class: true
  application:
    name: UI-Service
  cloud:
    config:
      enabled: false

security:
  user:
    password: none
  oauth2:
    client:
      accessTokenUri: http://localhost:9999/uaa/oauth/token
      userAuthorizationUri: http://localhost:9999/uaa/oauth/authorize
      clientId: client
      clientSecret: password
    resource:
      jwt:
        keyValue: |
          -----BEGIN PUBLIC KEY-----
          MIIBIjANBgkqhkiG9w0BAQEFAAOCAQ8AMIIBCgKCAQEAgrS/8BOdDPptVdulZ58b
          gt8EChTvTH0M6XvSMDMArVVBqD1AZXsS3ULLxdZxRGGHDNrnjk5MP+SkKcIl0ND+
          ilJdSy5VV+nuOSl6lo1jrXI4ZRNi6rYrjIgVMP4SEt3qAGRvFQvSmHkcnBptu6YD
          dKVjeHy3GddOO+BvOX8bHNZ7dH6qlHi0AQNj3MNKaCMDVUt5rBQNoEZzv/wfbTcv
          v8q2bvThHR6M6kMzOBtLwAseIRqe6kOQ6Z5LRzHX/n0GdKsvrDFL8ynJrK9VmnYY
          E4DkVoT/sLG0XgfnLzLsnS6R/8XZb/gas0+TguiPOcnh7q/tzEDfT6MbGMXKlmmS
          XQIDAQAB
          -----END PUBLIC KEY-----

zuul:
  routes:
    resource:
      path: /resource/**
      url: http://localhost:9000/resource
    user:
      path: /user/**
      url: http://localhost:9999/uaa/user

logging:
  level:
    org.springframework.security: DEBUG

eureka:
  client:
    serviceUrl:
      # for Docker Container
      #defaultZone: http://eureka:8761/eureka/
      # for local usage
      defaultZone: http://localhost:8761/eureka/
  instance:
    leaseRenewalIntervalInSeconds: 10
    statusPageUrlPath: /info
    healthCheckUrlPath: /health